name: Test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run unit tests
        run: yarn test:unit

      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          start: yarn dev
          command: yarn test:e2e
          wait-on: http://127.0.0.1:8080

      - name: Run build
        run: yarn build
